name: flutter_lorem_picsum
description: Lorem Picsum Application using Flutter

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # state management
  flutter_bloc: ^8.0.0
  equatable: ^2.0.3
  # networking
  http: ^0.13.4
  # image caching
  cached_network_image: ^3.2.0
  flutter_cache_manager: ^3.3.0
  # ability to view and scale images
  photo_view: ^0.13.0
  # ability to save image to gallery
  gallery_saver: ^2.3.2
  # ability to share photo
  share: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  bloc_test: ^9.0.1

flutter:
  uses-material-design: true